export { CodeGen, NAMES, Scope, pathJoinExpr, quoteString, rawExpr } from "./codegen/index.js";
export type { PathSegmentLike, RawExpression } from "./codegen/index.js";
export {
  compileSchema,
  createDeps,
  deepEqual,
  typeOf,
  wrapErrors,
  type CompileOptions,
  type CompiledSchema,
  type Validator,
  type ValidatorDeps,
  type ValidationResult,
} from "./compiler/index.js";
export {
  APPLICATOR_VOCAB,
  CORE_VALIDATION_VOCAB,
  FORMAT_VOCAB,
  additionalPropertiesKeyword,
  allOfKeyword,
  anyOfKeyword,
  applicatorVocabulary,
  constKeyword,
  containsKeyword,
  createKeywordContext,
  defaultVocabularies,
  dependentRequiredKeyword,
  dependentSchemasKeyword,
  enumKeyword,
  exclusiveMaximumKeyword,
  exclusiveMinimumKeyword,
  formatKeyword,
  formatVocabulary,
  ifThenElseKeyword,
  itemsKeyword,
  maxItemsKeyword,
  maxLengthKeyword,
  maxPropertiesKeyword,
  maximumKeyword,
  minItemsKeyword,
  minLengthKeyword,
  minPropertiesKeyword,
  minimumKeyword,
  multipleOfKeyword,
  notKeyword,
  oneOfKeyword,
  patternKeyword,
  patternPropertiesKeyword,
  prefixItemsKeyword,
  propertiesKeyword,
  propertyNamesKeyword,
  requiredKeyword,
  typeKeyword,
  uniqueItemsKeyword,
  validationVocabulary,
  type EmitErrorParams,
  type KeywordCompileContext,
  type KeywordContextInputs,
  type KeywordDefinition,
  type Vocabulary,
} from "./keywords/index.js";
export {
  SchemaRegistry,
  resolve,
  type ResolvedGraph,
  type ResolveOptions,
} from "./resolve/index.js";
